### ISSUE TITLE
Solve the remote and exploratory visualization problems

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#108]
This is mostly a documentation of some issues that @jypeter expressed to me at the ESGF Face to Face; I'm sticking it here, because this seems like the right place.

A fundamental issue that our users have right now is that X forwarding is slow, VNC is flaky, and there's no really great way to be able to do exploratory analysis on a remote system.

Using VCS from the python console also has some issues for exploratory visualization (the required call to x.interact(), the general wonky behavior of our interactive mode, and that you can't update the visualizations while still being able to interact with them).

The solution that we've been recently thinking about for this is jupyter notebooks. They're pretty friendly, but some folks (like @jypeter) prefer the console for a variety of legacy reasons.

I would posit that this is a place where we can use VCS.js' server-side rendering mode to improve the user experience. I don't have a fully formed idea in my head yet, but something akin to this:

1) Launch `vcs-server` on the remote system
2) Have a "remote" mode for VCS that proxies commands to the remote system
3) View the results in the browser

The one major issue I see with this approach would be that most servers block all but a select few ports. If we define a specific range that vcs-server will launch on, and have some kind of authentication for proxying to said server, I think we could probably pass muster for most facilities and get them to open a port range.

This would also allow us to do a kind-of-dumb but user experience friendly thing as well; the vcs-server could be run locally, users could use the remote mode to proxy commands to a separate python process, and view visualizations locally in the browser and still have the ability to update the visualization without using `interact()`.

Another thing this gives us is the ability to move big computation all onto bigger iron, though it will require some thinking about how to handle the data in a way that supports it.

Thoughts? Don't really know what the priority on this for the team is, certainly should wait until we have vcs.js hardened up a bit. I'm really just trying to document and flesh out some ideas bouncing around my head, post-conference.

**Comment by durack1** [comment]
@chaosphere2112 good idea to drop ideas down somewhere.. I really do like the ability to animate/movie view data, as it's kinda amazing what you see when you can scroll around the temporal extension of a gridded dataset.. I'd be happy to chip in on this conversation thread maybev next year when we're all in the building?

**Comment by doutriaux1** [comment]
VCDAT 2.0 fixes this, kitware wants to bring back interaction in vcdat.
