### ISSUE TITLE
 bg=True freaks out on OSMesa builds

### ISSUE THREAD

**Issue by danlipsa** [CDAT/vcs#119]
See:

https://github.com/UV-CDAT/vcs/issues/117

**Comment by durack1** [comment]
@danlipsa @doutriaux1 just for old times sake, this is related to #72, #71, #70, UV-CDAT/uvcdat#1424, and UV-CDAT/uvcdat#1397 (closed)

**Comment by doutriaux1** [comment]
tested on mac and linux with 8.1 it works for me.
