### ISSUE TITLE
Bring back x.colormapgui() (and add color related resources on the web/wiki)?

### ISSUE THREAD

**Issue by jypeter** [CDAT/vcs#140]
@doutriaux1 I have just spent some time on the web site and wiki looking for some information/documentation about **vcs and colors**. Either I have been very unlucky, or there is no web page on this rather important topic. I have even started _uvcdat_ in case I quickly saw some menu about color.

I vaguely remember discussions about _viridis_, _transparency_ and other color related stuff but I have not found any page about this. I have found https://github.com/UV-CDAT/uvcdat/issues/906

Would it be possible to bring back the old **x.colormapgui()** method in vcs, or something similar? This could maybe help people. And at least have a dedicated web page about colors, showing the available colormaps

For the people who never knew this nice vcs panel, I have added below the content of **help(x.colormapgui)**
```
Help on method colormapgui in module vcs.Canvas:

colormapgui(self, gui_parent=None, transient=0, max_intensity=None) method of vcs.Canvas.Canvas instance
    Function: colormapgui
    
    Description of Function:
       Run the VCS colormap interface.
    
       The colormapgui command is used to bring up the VCS colormap interface. The interface
       is used to select, create, change, or remove colormaps.
    
    Example of Use:
       a=vcs.init()
       a.colormapgui()
       a.colormapgui(max_intensity = 255)
(END)
```

I have also added below a few of the old (September 2011!) screenshots I made of colormapgui, in order to help me work with colors
![vcs_rainbow](https://cloud.githubusercontent.com/assets/2785573/23712243/9d46e8ec-0422-11e7-97d2-7eba40262bed.png)

![vcs_rainbow_no_grn](https://cloud.githubusercontent.com/assets/2785573/23712254/a5a3ac5a-0422-11e7-9306-1f0b41505376.png)

![vcs_amip](https://cloud.githubusercontent.com/assets/2785573/23712259/a9121a48-0422-11e7-9b17-012a491ca83c.png)

**Comment by doutriaux1** [comment]
@chaosphere2112 @mattben do you think it would be possible to have this function fireup `vcdat` and bring in the colormap editor? That would be awesome!

**Comment by durack1** [comment]
@chaosphere2112 @mattben @doutriaux1 @jypeter 👍 from me too.. Having the colormaps (and all the options) exposed would be great.. Documentation would make UV-CDAT great again..

**Comment by mattben** [comment]
https://uvcdat.llnl.gov/docs/vcs/misc/colormap.html ??

**Comment by durack1** [comment]
This relates to some discussion at https://github.com/UV-CDAT/uvcdat/issues/1345#issuecomment-161110687 (and some palette examples) and also https://github.com/UV-CDAT/uvcdat/issues/1345#issuecomment-162099427 further down the same page

**Comment by chaosphere2112** [comment]
@jypeter @durack1 @doutriaux1 Not on the timeline for this release. There's no technical reason why we couldn't do this (assuming python's webbrowser module works on your machine). There's technically no reason we couldn't look at going full-bore into the old-school VCS style, where you could launch an editor for anything you're working on. We wouldn't need to launch all of VCDAT, just a small page that uses the `vcs-widgets` package to render the editor (basically the same way that the Jupyter integration will work) and a embedded HTTP server to handle the "save" action.

**Comment by doutriaux1** [comment]
@chaosphere2112 obviously not for this release (code freeze already happened anyway) but yes for CDAT 1.0 (or a beta before that).

**Comment by doutriaux1** [comment]
this will be part of VCDAT 2 and can be done in VCDAT 1.0
