### ISSUE TITLE
Automatic xticlabels2 and yticlabels2 don't work

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#142]
When plotting using the default values for graphics methods' `yticlabels2` and `xticlabels2`, the automatic value (`'*'`) doesn't work (default template hides those labels, so it's been going unnoticed for who knows how long; as a sidenote, we should probably test using a template with every field enabled).

```python
import vcs
data = [range(10) for i in range(10)]
x = vcs.init()
tmpl = vcs.createtemplate()
tmpl.ylabel2.priority = 1
tmpl.xlabel2.priority = 1
x.plot(data, tmpl)
```

![bad](https://cloud.githubusercontent.com/assets/718512/23767287/e980846c-04bc-11e7-8079-0362b6c27605.png)

**Comment by doutriaux1** [comment]
@doutriaux1 fixed that when wrting templates notebook
