### ISSUE TITLE
vector plots use wrong scale for geographic projection

### ISSUE THREAD

**Issue by danlipsa** [CDAT/vcs#149]
The following code scales the vectors based on the bounding box of the actor if we have geographic projection. This is wrong as the bounding box for vectors is usually smaller than the bounding box for the dataset. See streamlines for the correct way to handle this.

 if self._vtkGeoTransform is None:
            wc = plotting_dataset_bounds
 else:
            xrange = list(act.GetXRange())
            yrange = list(act.GetYRange())
            wc = [xrange[0], xrange[1], yrange[0], yrange[1]]

**Comment by scottwittenburg** [comment]
I have a few questions on this one @danlipsa:

1.  It's not obvious to me why the bounding box for vectors would be smaller than the bounding box for the dataset?  Can you provide a brief explanation?

2. When you created this issue, diid you have some plot that you could see was wrong?  

3. Or was is just that you saw the code and recognized an error?  

4. Is the code you pasted in `vectorpipeline.py`?

**Comment by danlipsa** [comment]
@scottwittenburg I think this is solved isn't it? We solved this by sampling the dataset, first along boundary and how on the whole dataset. I don't see inside vectorpipline or anywhere else this code.

**Comment by scottwittenburg** [comment]
@danlipsa You could be right about that.  When I added those questions, it was because I couldn't find the code you pasted in the original issue.

**Comment by danlipsa** [comment]
@scottwittenburg Sorry, I did not see those at the time. Lets close this then. @doutriaux1 Any objections?

**Comment by doutriaux1** [comment]
I think you're right.
