### ISSUE TITLE
Problems importing vcs-nox, fails with ImportError: No module named vtkRenderingOpenGLPython

### ISSUE THREAD

**Issue by durack1** [CDAT/vcs#151]
@doutriaux1 @zshaheen I have just tried to reinstall a version of `vcs-nox` from the nightly channel and have got this error:
```
public1:/home/p1d> conda create -n PMP-noxNightly2Test -c conda-forge -c uvcdat/label/nightly -c uvcdat -c pcmdi/label/nightly pcmdi_metrics-nox
public1:/home/p1d> bash
bash-4.1$ source activate PMP-noxNightly2Test
(PMP-noxNightly2Test) bash-4.1$ which python
/home/p1d/anaconda2/envs/PMP-noxNightly2Test/bin/python
(PMP-noxNightly2Test) bash-4.1$ python
Python 2.7.13 | packaged by conda-forge | (default, Mar 20 2017, 14:04:17)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2Test/lib/python2.7/site-packages/vcs/__init__.py", line 57, in <module>
    from utils import *  # noqa
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2Test/lib/python2.7/site-packages/vcs/utils.py", line 25, in <module>
    import vtk
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2Test/lib/python2.7/site-packages/vtk/__init__.py", line 89, in <module>
    from .vtkRenderingOpenGL import *
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2Test/lib/python2.7/site-packages/vtk/vtkRenderingOpenGL.py", line 9, in <module>
    from vtkRenderingOpenGLPython import *
ImportError: No module named vtkRenderingOpenGLPython
```
The issue appears to have occurred after 15th March, as I used the same commandline to install an identical environment and that is working fine. It looks like the `vcs-nox` version and the `vcs` versions are getting tangled up (I assume the `OpenGL` references are removed in the `nox` versions)

**Comment by durack1** [comment]
@danlipsa you might have some insights with this..

**Comment by durack1** [comment]
@zshaheen the only difference that I can ascertain between these two environments is that the `CDP` was updated from `1.0.2` (PMP-noxNightly2, which works) to `1.0.3` (PMP-noxNightly2Test, which doesn't work) between these installs:
```
public1:/home/p1d> ls -al anaconda2/envs/PMP-noxNightly2/conda-meta/ | grep cdp
-rw-r--r--  1 Paul.Durack b    761 Mar 15 17:33 cdp-1.0.2-0.json
public1:/home/p1d> ls -al anaconda2/envs/PMP-noxNightly2Test/conda-meta/ | grep cdp
-rw-r--r--  1 Paul.Durack b   2115 Mar 22 13:32 cdp-1.0.3-0.json
```

**Comment by zshaheen** [comment]
@durack1 The updated version of cdp couldn't have caused the vtk issues, since there aren't any dependencies. However, you can still `conda remove cdp` and reinstall 1.0.2. 

Otherwise, I'm not really sure why the vtk OpenGL module is missing.

**Comment by durack1** [comment]
@zshaheen I just attempted to roll back to `1.0.2` to see if this fixes me, and it appears to not solve the issue:
```
public1:/home/p1d> conda create -n PMP-noxNightly2TestCDP -c conda-forge -c uvcdat/label/nightly -c uvcdat -c pcmdi/label/nightly pcmdi_metrics-nox cdp=1.0.2
public1:/home/p1d> bash
bash-4.1$ source activate PMP-noxNightly2TestCDP
(PMP-noxNightly2TestCDP) bash-4.1$ which python
/home/p1d/anaconda2/envs/PMP-noxNightly2TestCDP/bin/python
(PMP-noxNightly2TestCDP) bash-4.1$ python
Python 2.7.13 | packaged by conda-forge | (default, Mar 20 2017, 14:04:17)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2TestCDP/lib/python2.7/site-packages/vcs/__init__.py", line 57, in <module>
    from utils import *  # noqa
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2TestCDP/lib/python2.7/site-packages/vcs/utils.py", line 25, in <module>
    import vtk
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2TestCDP/lib/python2.7/site-packages/vtk/__init__.py", line 89, in <module>
    from .vtkRenderingOpenGL import *
  File "/home/p1d/anaconda2/envs/PMP-noxNightly2TestCDP/lib/python2.7/site-packages/vtk/vtkRenderingOpenGL.py", line 9, in <module>
    from vtkRenderingOpenGLPython import *
ImportError: No module named vtkRenderingOpenGLPython
```

**Comment by durack1** [comment]
@zshaheen this is the `-nox` install, so it's not clear to me that the OpenGL stuff should be included anyway?

**Comment by doutriaux1** [comment]
@durack1 solution is updated on the website you need:
```
conda create -n uvcdat -c uvcdat/label/2.8 -c conda-forge -c uvcdat uvcdat-nox —show-channel-urls
```

**Comment by doutriaux1** [comment]
nightlies should  work out of the box:
```
conda create -n crap  -c conda-forge -c uvcdat/label/nightly -c uvcdat uvcdat-nox —show-channel-urls
```

**Comment by durack1** [comment]
@doutriaux1 with the example:
```
conda create -n PMP-noxNightly2Test -c conda-forge -c uvcdat/label/nightly -c uvcdat -c pcmdi/label/nightly pcmdi_metrics-nox
```
It wasn't working this morning..

**Comment by doutriaux1** [comment]
@durack1 yep looks like we need to specifically tell it to use a newer vtk-cdat-nox, odd

```
conda create -n PMP-noxNightly2Test -c conda-forge -c uvcdat/label/nightly -c uvcdat -c pcmdi/label/nightly pcmdi_metrics-nox 'vtk-cdat-nox>7.1.0.2017.3;'
```

**Comment by durack1** [comment]
@doutriaux1 I can confirm that with `vtk-cdat-nox 7.1.0.2017.1.20-py27_0 uvcdat/label/nightly` your line above](https://github.com/UV-CDAT/vcs/issues/151#issuecomment-288570089) fails, so reopening

**Comment by doutriaux1** [comment]
@durack1 is my last line working with the `>` ?

**Comment by durack1** [comment]
@doutriaux1 success!
```
public1:/home/p1d> conda create -n PMP-noxNightly2Test -c conda-forge -c uvcdat/label/nightly -c uvcdat -c pcmdi/label/nightly pcmdi_metrics-nox "vtk-cdat-nox>7.1.0.2017.3"

Installs: vtk-cdat-nox: 7.1.0.2017.3.14-py27_0 uvcdat/label/nightly
```
and the success part:
```
public1:/home/p1d> bash
bash-4.1$ source activate PMP-noxNightly2Test
(PMP-noxNightly2Test) bash-4.1$ python -c "import vcs; x=vcs.init(); x.plot([1,2,3])"
(PMP-noxNightly2Test) bash-4.1$
```

**Comment by durack1** [comment]
@doutriaux1 I would purge the `7.1.0.2017.1.20-py27_0` version, that seems to be the issue

**Comment by doutriaux1** [comment]
@durack1 try again it's purged, I suspect you'll get 2.8 though...

**Comment by durack1** [comment]
@doutriaux1 with the command-line:
```
conda create -n PMP-noxNightly2TestUpdate -c conda-forge -c uvcdat/label/nightly -c uvcdat -c pcmdi/label/nightly pcmdi_metrics-nox
```
I get:
```
vcs-nox: 2017.2.22-py27_0 uvcdat/label/nightly
vtk-cdat-nox: 7.1.0.2.8-py27_2 uvcdat
```
So it's not quite solved.. Is the solution moving everything to `conda-forge` or something else?

**Comment by doutriaux1** [comment]
yep something in uvcdat forces it to go down to 2.8, I'll upload a uvcdat nightly

**Comment by durack1** [comment]
@doutriaux1 let me know when it's in, and I'll run a test before letting the GFDL folks have a go..

**Comment by zshaheen** [comment]
@doutriaux1 Follow your suggestion of setting `vtk-cdat-nox>7.1.0.2017.3` everything was fine.

But since a few days ago, things have been messing up for people. Even after you degrade vtk-cdat-nox to a confirmed working nightly, I still get the vtkRenderingOpenGLPython error. 

The problem is mesalib. The latest code of something (vtk-nox, vtk-cdat?) uses 17.0.3 instead of 7.6.1. Installing 7.6.1 fixes it. 

Charles, is there a way to fix this issue without having the user manually install 7.6.1 of mesalib? You know how these climatologists are about this stuff. Thanks.

**Comment by zshaheen** [comment]
@doutriaux1 Here are the installed packages for both envs btw. Broken one is the left side, working one is on the right side. Again, the different versions of vcs-nox wasn't the problem.
https://www.diffchecker.com/mss4MqSc

**Comment by doutriaux1** [comment]
@zshaheen you need to add `"mesalib<8"` for now we are upgrading to 17 and conda-forge is already serving it up.
