### ISSUE TITLE
Taylor diagram loses y-axis with 2.12 version

### ISSUE THREAD

**Issue by lee1043** [CDAT/vcs#253]
I am testing the Taylor Diagram with 2.12 version but it looks like it is losing y-axis as showing below. 

![index](https://user-images.githubusercontent.com/17091564/30301647-daf593b0-9710-11e7-9673-dba2e58b5ab9.png)

```python
# Create dummy 7 data
import MV2
corr = [.2, .5, .7, .85, .9, .95, .99]
std = [1.6, 1.7, 1.5, 1.2 , .8, .9, .98]
data = MV2.array(zip(std, corr))
data.id = "My Taylor Diagram Data"

import vcs
taylor = vcs.createtaylordiagram()
x=vcs.init()
x.plot(data,taylor)
```

It also gives warning as below, not sure it is related to lose y-axis. 

```
/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/numpy/ma/core.py:6385: MaskedArrayFutureWarning: In the future the default for ma.maximum.reduce will be axis=0, not the current None, to match np.maximum.reduce. Explicitly pass 0 or None to silence this warning.
  return self.reduce(a)
/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/numpy/ma/core.py:6385: MaskedArrayFutureWarning: In the future the default for ma.minimum.reduce will be axis=0, not the current None, to match np.minimum.reduce. Explicitly pass 0 or None to silence this warning.
  return self.reduce(a)
```

**Comment by lee1043** [comment]
@doutriaux1 Sorry, accidentally clicked assigning part, but maybe it was right?

**Comment by doutriaux1** [comment]
@lee1043 are you using mesa or not? I generated the jupyter notebooks with mesa and I don't see this issue

**Comment by jypeter** [comment]
@lee1043 Charles has apparently fixed the Warning (https://github.com/UV-CDAT/genutil/issues/14). I initially also got this warning when using vcs (boxfill plot), but I attributed it to `genutil.minmax` since it was mentioning both _minimum_ and _maximum_.

There could of course be some stray minimum and maximum calls not using _minmax_ out there

**Comment by lee1043** [comment]
@doutriaux1 How I can see if I am using mesa?

```
$ conda list mesa
# packages in environment at /Users/lee1043/anaconda2/envs/uvcdat-2.12:
#
````

Not sure this is right way to check. Does mesa come with uvcdat-2.12 conda install?

**Comment by doutriaux1** [comment]
@lee1043 that's the right way. Ok it means you're not using mesa in this environment. Thanks I'll take a look. @danlipsa any idea?

**Comment by doutriaux1** [comment]
@lee1043 you can choose with or without mesa, simply add `mesalib` to the command line or install `mesalib` after the fact. I will update the instructions page to make this clearer.

**Comment by lee1043** [comment]
@doutriaux1 Thanks, but it seems like ```conda install mesalib``` does not work.  Did I miss something?

```
$ conda install mesalib
Fetching package metadata .........

PackageNotFoundError: Package missing in current osx-64 channels: 
  - mesalib

Close matches found; did you mean one of these?

    mesalib: kealib
```

**Comment by lee1043** [comment]
@jypeter @doutriaux1 Thanks for inform. Does this correction included in the nightly version?

**Comment by zshaheen** [comment]
@lee1043 Here's the command to install mesalib:
```
conda install mesalib -c conda-forge -c uvcdat
```

**Comment by lee1043** [comment]
@zshaheen Thanks, it works. @doutriaux1 Having ```mesalib``` fixed the issue. Thanks.

**Comment by doutriaux1** [comment]
@lee1043 that's how I made the notebook. I need to figure out why non mesa does not work. @danlipsa any idea?

**Comment by danlipsa** [comment]
@doutriaux1 Maybe it is clipped by the clip planes in fittoviewport (the clip plane and the axis have the same coordinates, one implementation chooses to clip the other chooses to let it pass)?
