### ISSUE TITLE
Misc 'bg' questions/problems (2.12)

### ISSUE THREAD

**Issue by jypeter** [CDAT/vcs#257]
@doutriaux1 @danlipsa I have copy/pasted https://uvcdat.llnl.gov/Jupyter/Basic_VCS_demo/Basic_VCS_demo.html after reading https://github.com/UV-CDAT/vcs/issues/256

The first time I did not pay attention and kept `bg=True`, which led me to notice the following things:
- I thought I could use `x.showbg()` in order to have a look at the canvas, but **showbg is still missing**. Seems like [you reported the missing showbg 2 years ago](https://github.com/UV-CDAT/vcs/issues/71)
- it seems that once you have specified a bg value for a canvas, **you can't go back and use the opposite bg value**. More details below. Hmmm, looks to be https://github.com/UV-CDAT/vcs/issues/72 (except I'm giving more details!)...

If I use
```
bg=True
x.plot(s,bg=bg)
```
and then
```
x.clear()
x.plot(s)
```
or `x.plot(s, bg=False)`
the **_x_ canvas won't be displayed**

On the other hand, if I do
```
y = vcs.init()
y.plot(s)
```
the canvas is correctly displayed

Now if I type
```
>>> y.clear()
>>> y.plot(s, bg=True)
<vcs.displayplot.Dp object at 0x2b23c21ca530>
>>> y.interact()
/home/share/unix_files/cdat/miniconda2/envs/cdatm16/lib/python2.7/site-packages/vcs/VTKPlots.py:129: UserWarning: Press 'Q' to exit interactive mode and continue script execution
  "Press 'Q' to exit interactive mode and continue script execution")
```
The **canvas is displayed despite bg=True** and I can enter interactive mode!

Things get weirder if I close the canvas
```
>>> y.clear()
>>> y.close()
>>> y.plot(s, bg=True)
<vcs.displayplot.Dp object at 0x2b23c21ca530>
>>> y.interact()
/home/share/unix_files/cdat/miniconda2/envs/cdatm16/lib/python2.7/site-packages/vcs/VTKPlots.py:126: UserWarning: Cannot start interaction. Blank plot?
  warnings.warn("Cannot start interaction. Blank plot?")
```
My canvas will still (re)open, with the (previous?) **plot displayed on a black background**, and I get the blank plot warning

**Comment by doutriaux1** [comment]
@danlipsa what do you think, should we ignore the `bg` argument in plot functions, and force the above way to do it?

**Comment by danlipsa** [comment]
@doutriaux1 Yes, I think we should. I think we only need to render in the background when canvas is foreground and we want a png with different resolution than the canvas. They user should not access that.
