### ISSUE TITLE
Plot creates new graphics method objects

### ISSUE THREAD

**Issue by danlipsa** [CDAT/vcs#268]
Plotting a boxfill with a given graphics method still creates a new graphics method. Why?

Also, when we do not pass our own graphics method, a new gm is created, but we don't know its name so that we can delete it. We should provide a why to access the name of the gm created so that we can deleted after we plot.

@doutriaux1 Do you remember the reason why graphics methods are created in the plot function? We seem to look at the data and modify gm parameters based on that. Is that the motivation behind this? Why not changing the gm that is passed as a parameter than? 

<pre>
>>> import vcs
>>> import cdms2
>>> vcs.download_sample_data_files()
>>> f=cdms2.open(vcs.sample_data+"/clt.nc")
>>> s=f("clt")
>>> x=vcs.init()
>>> gm = vcs.createboxfill('myboxfill')
>>> vcs.elements['boxfill'].keys()
['polar', 'a_lambert_boxfill', 'default', 'a_boxfill', 'a_polar_boxfill', 'a_robinson_boxfill', 'a_mollweide_boxfill', 'myboxfill', 'quick', 'robinson']
>>> x.plot(s, gm)
<vcs.displayplot.Dp object at 0x7f03ac98bb48>
>>> vcs.elements['boxfill'].keys()
['polar', 'a_lambert_boxfill', 'default', 'a_boxfill', 'a_polar_boxfill', '__boxfill_511997554805793', 'a_robinson_boxfill', 'a_mollweide_boxfill', 'myboxfill', 'quick', 'robinson']
</pre>

**Comment by danlipsa** [comment]
@aashish24 Any comments on this?

**Comment by doutriaux1** [comment]
@danlipsa we make copy of the gm for MANY reasons such as changing labels, title, etc... changing default levels,  sometime we also create new templates, for aspect ratios etc... But I thought they were cleaned up automatically once the canvas is cleared.

**Comment by danlipsa** [comment]
@doutriaux1 If that's the case, it is fine even if a little disconcerting to new users such as myself. :smile:

**Comment by doutriaux1** [comment]
@danlipsa can you double check it goes away after a clear? Do you think we should add a special "tag" in the name so that we do not list "nuder the hood autogenerated" objects in the list functions?

**Comment by doutriaux1** [comment]
also you should use `vcs.listelements("boxfill")` not `vcs.elements["boxfill"].keys()` because the last one is the *developer* hook and could change in the future whereas the first one is the official API call

**Comment by danlipsa** [comment]
Yes, it does go away when you call clear. I do think we should add a special tag and not list those graphics methods as the user has no idea what they are and who created them. In my mind, they should be deleted after plot finishes as are never used again. But its a low priority task as long as we delete everything on clear. Thanks for the listelements tip.

**Comment by danlipsa** [comment]
This might come up for vcdat as users might browse through all graphics methods and might be confused by these temporary gm-s. Will see ...
