### ISSUE TITLE
UV-CDAT logo does not show up in PDF/is invalid in Acrobat Reader

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#31]
```
import vcs
x = vcs.init()
x.plot([range(5) for i in range(5)])
x.pdf("breaks_in_acrobat")
```

Open the PDF in Preview on a mac, and you get an image without the logo. Open the PDF in acrobat and apparently you get a scary error message.

**Comment by aashish24** [comment]
Thanks for the bug report @chaosphere2112 we will push a fix asap @williams13

**Comment by danlipsa** [comment]
@aashish24 I'll take a look at this.

**Comment by williams13** [comment]
Thanks Dan!

Best regards,
Dean

**Comment by danlipsa** [comment]
This seems to be a bug in VTK:
https://gitlab.kitware.com/vtk/vtk/issues/16909

**Comment by doutriaux1** [comment]
works for me in 8.1
