### ISSUE TITLE
Tick label size adjustment

### ISSUE THREAD

**Issue by lee1043** [CDAT/vcs#339]
Is there any simple way to adjust font size for the tick labels, such as something like `iso.xticklabels1.fontsize=10`? I am struggling with too small font size for x,y tick labels and legend labels, couldn't find option to control the font size. Thanks!

<img width="703" alt="screen shot 2018-05-11 at 2 55 01 pm" src="https://user-images.githubusercontent.com/17091564/39948542-51f990dc-552b-11e8-9ab3-a6251f34b62e.png">

**Comment by doutriaux1** [comment]
@lee1043 this is controlled via the template. I really need to do the notebook for template!

```python
import vcs
templ = vcs.createtemplate()
to = vcs.createtextorientation()
to.height=20. # BIG!
templ.xlabel1.textorientation = to
x.plot(data,templ)
```

**Comment by lee1043** [comment]
@doutriaux1 thanks, what about tick label over the color bar?

**Comment by doutriaux1** [comment]
```python
templ.legend.textoriention = To
```

**Comment by lee1043** [comment]
![screen shot 2018-05-11 at 3 16 06 pm](https://user-images.githubusercontent.com/17091564/39949200-405a0ec6-552e-11e8-8f17-5d52dbfc55a8.png)

@doutriaux1 thanks, it is helpful. Do you have something similar for xticlabel1 location adjustment? On left side labels are overlapping with line.

**Comment by lee1043** [comment]
@doutriaux1 one more question, can I move colarbar labels upward, so give some distance between numbers and colorbar?

**Comment by doutriaux1** [comment]
@lee1043 
```python
templ.legend.y1 + =.05
templ.legend.y2 + =.05
```

**Comment by doutriaux1** [comment]
@lee1043 sorry what you want is:
```python
templ.legen.offset += .05
```

**Comment by lee1043** [comment]
@doutriaux1 but that moves colorbar itself. I want to fix colorbar but only move legend numbers above colorbar to upward, so bottom of numbers don't meet the upper line of colorbar

**Comment by lee1043** [comment]
@doutriaux1 yes, thanks!

**Comment by lee1043** [comment]
`templ.legend.offset += .01` works as I wanted. Thanks!

<img width="701" alt="screen shot 2018-05-11 at 3 32 16 pm" src="https://user-images.githubusercontent.com/17091564/39949585-821bdda6-5530-11e8-8ab0-dcd3fd46e81e.png">
