### ISSUE TITLE
transparency does not work for text

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/vcs#396]
```python
import vcs
  
x = vcs.init()

fa = vcs.createfillarea()
fa.x = [.4,.6,.6,.4]
fa.y = [.4,.4,.6,.6]
fa.color="red"

x.plot(fa)

txt = vcs.createtext()
txt.string = "TRANSPARENT STRING"
txt.angle = -45
txt.x = .5
txt.y = .5
txt.halign="center"
txt.valign = "half"
txt.color = "blue"
txt.height = 35
x.plot(txt)

x.png("transp_text")
```

**Comment by doutriaux1** [comment]
![transp_text](https://user-images.githubusercontent.com/2781425/55083029-00ae0d80-5060-11e9-80ff-21e419a03855.png)

**Comment by scottwittenburg** [comment]
@doutriaux1  I must be missing something here.  Which property on the `txt` is supposed to set the transparency?

**Comment by doutriaux1** [comment]
the color

**Comment by scottwittenburg** [comment]
But then how does setting the color to "blue" do that?

**Comment by doutriaux1** [comment]
oh sorry probably was a bad copy/paste job 😆 
use
```python
txt.color = [0,0,100,50]
```

**Comment by doutriaux1** [comment]
BTW
```python
txt.color = [0,0,100,0]
```

Does make it go away

**Comment by scottwittenburg** [comment]
Ah, gotcha.

I've played with it now, and it seems that VTK expects a floating point number between 0 and 1.  If you try with 0.5, you'll see it's working.  So it's just a matter of knowing what the user is expected to input and mapping that into [0.0, 1.0] properly.

Looks like the rest of the color components are expected to be given by the user in the range [0, 100]?

**Comment by doutriaux1** [comment]
in isofill test double check but i'm pretty sure the opacity is sent from user in the 0-100 range as well

**Comment by doutriaux1** [comment]
let's ,make it uniform

**Comment by scottwittenburg** [comment]
I'll put together a PR for it.

**Comment by doutriaux1** [comment]
thx
