### ISSUE TITLE
Problem in continents lines 

### ISSUE THREAD

**Issue by arulalant** [CDAT/vcs#436]
Dear CDAT Team,

I am plotting world continents using cdat8.1, but there seems to be a problem. Please see attached sample plot, in which can be seen four straight lines connecting different regions. This kind of problem is not seen when I plot using uvcdat1.5.1 (and cdat5.2) version (by using same shape file). Could you please guide me to fix it ?
![test](https://user-images.githubusercontent.com/1246493/73592804-26037780-44cc-11ea-9860-10edb68a7cef.png)

**Comment by jypeter** [comment]
Do you need the country boundaries? Have you tried plotting only the continents?

If it works (no extra straight lines), it will only be a temporary workaround anyway

**Comment by arulalant** [comment]
Yes, I want the country boundaries, I made custom data_contienent_other12 by converting shape file into text file. I am plotting this via v.plot(data, boxfill, continents=12) where data is fully zero and zero is filled with white color, and legend is off.

Please let me know if I want to plot custom continents via shapefile, I can give a try.

Thanks.

**Comment by arulalant** [comment]
I am getting the following warnings while plotting the above continents.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 210 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 2200 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 2227 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 3353 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 3549 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 4230 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 4927 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 6794 with only one point, but VTK_LINE needs at least two points. Check the input.

Warning: In ../Common/DataModel/vtkPolyData.cxx, line 993
vtkPolyData (0x560bc13051a0): Building VTK_LINE 8113 with only one point, but VTK_LINE needs at least two points. Check the input.

**Comment by arulalant** [comment]
I fixed the problem.

There are many single point (lat, lon) in my data_continents_other12, say for example below is single lat,lon point in it.
 
2 1 21.539445 24.855263 85.832496 89.096366
22.167308 88.863479

The using vim edition version 7.4.326 (not working in version 8.1.1312), I find it by pattern matching "/\<2 1\>" then delete that line and next one line. Similarly, find all matches by pressing "n" character and delete two lines.

Here is the new plot.
![test](https://user-images.githubusercontent.com/1246493/73635217-0796ab00-4689-11ea-8363-f3555e2309f6.png)

So I am closing this issue.
Thanks & Regards,
Arulalan.T

**Comment by jypeter** [comment]
Great!
