### ISSUE TITLE
vcs cannot do sub and superscript anymore

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#48]
in 1.5.1 the follwoing used to work:

``` python
import vcs
x=vcs.init()
t=x.createtext()
t.string="E=mc!U2"
t.x=[.5]
t.y=[.5]
x.plot(t)
```

![mc2](https://cloud.githubusercontent.com/assets/2781425/17413165/ef62db38-5a34-11e6-9790-686c4f23550f.png)

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/2073

**Comment by doutriaux1** [comment]
now we are using matplotlib/tex syntax see: https://cdat.llnl.gov/Jupyter-notebooks/vcs/Mathematical_Expressions_and_Symbols/Mathematical_Expressions_and_Symbols.html
