### ISSUE TITLE
Isoline line, linecolors, and linewidths behave oddly

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#56]
So, there's some weirdness in the way we set up isoline objects.

```
IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import vcs
i
In [2]: isoline = vcs.createisoline()
```

If we do a .list(), we see our attributes:

```
In [3]: isoline.list()
 ----------Isoline (Gi) member (attribute) listings ----------
...
line =  ['solid']
linecolors =  [1]
linewidths =  [1.0]
...
```

If we set `.line` to the names of some line objects, some odd, but understandable behavior occurs:

```
In [4]: isoline.line = ["blue", "red"]

In [5]: isoline.list()
 ----------Isoline (Gi) member (attribute) listings ----------
...
line =  ['dash', 'dash']
linecolors =  [244, 242]
linewidths =  [2, 2]
...
```

It harvests the `type` attribute from the `blue` and `red` line objects, and sets those in `line`. It grabs the `color` attribute from each of them and sets `linecolors`. It grabs the `width` attribute and sets `linewidths`. All perfectly fine.

Now let's watch the world burn.

```
In [6]: isoline.line = ["green", "black"]

In [7]: isoline.list()
 ----------Isoline (Gi) member (attribute) listings ----------
...
line =  ['dash', 'dash']
linecolors =  [244, 242]
linewidths =  [2, 2]
...
```

Looks like... `linecolors` is exactly the same? Huh?

I'll make my own line object just to drive the point home:

```
In [8]: myline.list()
 ----------Line (Tl) member (attribute) listings ----------
secondary method = Tl
name = __line_787653798724505
type = ['dot']
width = [10]
color = [(0.0, 0.0, 100.0, 100.0)]
priority = 1
viewport = [0.0, 1.0, 0.0, 1.0]
worldcoordinate = [0.0, 1.0, 0.0, 1.0]
x = None
y = None
projection = default
colormap = None
```

I've set width, type, and color to be different from what was in isoline's attributes...

```
In [14]: isoline.line = [myline, myline]

In [15]: isoline.list()
 ----------Isoline (Gi) member (attribute) listings ----------
...
line =  ['__line_787653798724505', '__line_787653798724505']
linecolors =  [244, 242]
linewidths =  [2, 2]
...
```

OK, that's an extra bit of weird. Seems like instead of pulling the line's `type`, it pulled the line object's `name`... and still didn't update `linecolors` _or_ `linewidths`.

> **Aside:** Surprisingly, when plotted, this doesn't throw an error that `__line_787653798724505` isn't a valid line type; that's because when we plot, we create a graphics method that inherits from the one that is passed in, which grabs the line name and then does the above described behavior (loading the style, though not the `color` or `width`.

These issues can be traced back to the `isoline` module, and the behaviors of the `_setline` function. I think what happened is that at some point the default value of `linecolors` and `linewidths` changed from `None` to `[1]`, which makes it so it only replaces those values if you set `lines` to a list that has _more_ elements than you have in `linecolors` or `linewidths`. We should definitely alter that behavior; I think we probably should go to `None` triggering default values, rather than automatically filling in the defaults (that way we can "know" if a user has specified data, which we shouldn't automatically override when we set the `line` attribute).

There's one more issue, which is what happens when you do this:

```
In[16]: import cdms2

In[17]: f = cdms2.open(vcs.sample_data + '/clt.nc')

In[18]: s = f("clt")

In[19]: isoline.line = ["dash-dot"]

In[20]: isoline.linecolors = [250]

In[21]: isoline.linewidths = [25]

In[22]: x = vcs.init()

In[23]: x.plot(s, isoline)
```

which generates the below image:

![no_fat_level](https://cloud.githubusercontent.com/assets/718512/14726911/e15ebcde-07da-11e6-83de-db5bd75358c2.png)

As you can see, none of those lines have a width of 25, or a style of "dash-dot". That's because the "first" level is something like `[0, 0]` for the isoline, which is a very small chunk of the data, so it doesn't get displayed by VTK. We then pad out values for the rest of the levels, but we don't follow normal behavior for VCS. Every other place in VCS, when we pad out a list, we use the last value in the list, but in Isoline, we're using "solid" for `line` and `1.0` for `linewidths` (though we are using the last `color` for `linecolors`). This can be fixed in `isofillpipeline` by replacing the default values.

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1944

**Comment by doutriaux1** [comment]
line is gone.
