### ISSUE TITLE
"box" lines seem to be sometimes on sometimes off in vcs

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#69]
see:
https://open.cdash.org/testDetails.php?test=407803864&build=4178109

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1762

**Comment by doutriaux1** [comment]
@scottwittenburg looked carefully at these issues when switching to context2D

**Comment by scottwittenburg** [comment]
That old CDash link from years ago doesn't exist anymore, so it's hard to know what this was about.  I guess it makes sense to close it now, and if it comes up again, we'll create a new issue with more details.
