### ISSUE TITLE
update should try not to clear

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#79]
in VTKPlot.py the update function clears all display and redraws everything.

Now we have the update_input function that in most case (no change to template or graphic method) would be faster and would prevent a clear.

@dlonie I believe with your refactoring this update function should eventually be able to take advantage of the new pipeline even if a graphic method changed, right?

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1482

**Comment by doutriaux1** [comment]
code looks like it's been updated. closing.
