### ISSUE TITLE
vcs.plot(iso) creates text object that are not removed after clear

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#83]
Not related to #1397 (bg=1 memory leak)

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1424

**Comment by durack1** [comment]
@chaosphere2112 @doutriaux1 this is also an ongoing interest of mine - my batch script seems to be very good at highlighting the issue

**Comment by doutriaux1** [comment]
This has been cleared years ago.
