### ISSUE TITLE
Make VCS color palettes easier to edit/add

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#98]
It seems that the default color palettes are stored in the https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/Share/initial.attributes file, which contains color palettes as well as a bunch of other projection and other initialization info.. I wonder if there are also color palettes buried in the VTK installation directories too?

From a user's perspective (me) it would be nice if all the color palettes were contained in a single subdirectory, and adding a new palette file (assuming it follows standard format) to this directory will then be picked up upon the next initialization of UV-CDAT.

I'd be happy to work on this as a 2.2+ (2015+) milestone item, but would need some guidance from @doutriaux1 to kick things off

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/906

**Comment by durack1** [comment]
@chaosphere2112 @doutriaux1 I have a personal interest in this, so have added myself to be pinged..

**Comment by doutriaux1** [comment]
we added a matplotlib importer a while back. see tutorial: https://cdat.llnl.gov/Jupyter-notebooks/vcs/Colormap_Create/Color_map_create_own.html
